name: test_workflow

on: workflow_dispatch

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '8'
      - run: ./gradlew clean test
      - name: debug
        run: |
          pwd
          ls
          ls *
          ls **/build/test-results/
          echo "ls **/test-result*/"
          ls **/test-result*/
          echo "ls **/test-results/**/*.xml"
          ls **/test-results/**/*.xml
      - name: IntegTests
        run: |
          ./gradlew integTest
      
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            "**/test-results/**/*.xml"
