name: test_workflow

on: workflow_dispatch

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '8'
      - name: Unittests
        run: |
          ./gradlew clean test
      - name: IntegTests
        run: |
          ./gradlew integTest
